# Displays
	# Use Internal Screen
		# monitor= eDP-1, 1920x1080@144, auto, 1
		# monitor= HDMI-A-1, disable   # disable external screen
	
	# Use External Screen
		monitor= eDP-1, disable   # disable internal screen
		monitor= HDMI-A-1, 1920x1080@144, auto, 1

# Defaults Apps
$terminal = kitty
$fileManager = dolphin
$menu = wofi

# startup apps/daemons
exec-once = swaybg -i /home/tau/.config/hypr/assets/3.jpg -m fill 
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = hyprsunset
exec-once = waybar 
exec-once = hypridle

# hyprshot save directory
env = HYPRSHOT_DIR,/home/tau/hyprshot
